import { AiFillStar } from "react-icons/ai"; 
import basicphones1 from "../assets/1-Nokia-130-2023-dual-sim-light-gold.png"
import basicphones2 from "../assets/2-nokia-150-2023-dual-sim-Red.png"
import basicphones3 from "../assets/3-karbonn-k102i-black-grey.png"
import basicphones4 from "../assets/4-Karbonn-K31-Star-Blue.png"
import basicphones5 from "../assets/5-Lava-Gem-Power-Black.png"
import basicphones6 from "../assets/6-Lava-a1-vibe-2023-candy-blue.png"
import basicphones7 from "../assets/7-saregama-carvaan-m12-tamil-iris-orange.png"
import basicphones8 from "../assets/8-Saregama-carvaan-m22-tamil-black.png"
import basicphones9 from "../assets/9-itel-super-guru-600-champagne-gold.png"
import basicphones10 from "../assets/10-Itel-super-guru-400-deep-blue.png"
import basicphones11 from "../assets/11-Samsung-guru-music-2-sm-b315e-black.png"
const data = [
  {
    id:1,
    img: basicphones1,
    title: "Nokia 130 2023 dual sim",
    // star: <AiFillStar className="rating-star" />,
    // reviews: "(reviews)",
    // prevPrice: "₹ 1,59,900",
    Price: "3750",
    company: "hightolow",
    color: "gold",
    category: "nokia",
    discount: "5",
    inWishlist: false,
    inStock: true,
  },
  {
    id:2,
    img: basicphones2,
    title: "Nokia 150 2023 dual sim",
    star: <AiFillStar className="rating-star" />,
    reviews: "(reviews)",
    prevPrice: "₹ 1,19,900",
    Price: "4299",
    company: "hightolow",
    color: "red",
    category: "nokia",
    discount: "5",
    inWishlist: false,
    inStock: true,
  },

  {
    id:3,
    img: basicphones3,
    title: "karbonn k102i",
    star: <AiFillStar className="rating-star" />,
    reviews: "(reviews)",
    prevPrice: "₹ 89,900",
    Price: "899",
    company: "lowtohigh",
    color: "grey",
    category: "karbonn",
    discount: "5",
    inWishlist: false,
    inStock: false,
  },
  {
    id:4,
    img: basicphones4,
    title: "Karbonn K31",
    star: <AiFillStar className="rating-star" />,
    reviews: "(reviews)",
    prevPrice: "₹ 79,900",
    Price: "1249",
    company: "lowtohigh",
    color: "blue",
    category: "karbonn",
    discount: "5",
    inWishlist: false,
    inStock: true,
  },
  {
    id:5,
    img: basicphones5,
    title: "Lava Gem Power",
    star: <AiFillStar className="rating-star" />,
    reviews: "(reviews)",
    prevPrice: "₹ 1,02,999",
    Price: "1849",
    company: "lowtohigh",
    color: "black",
    category: "lava",
    discount: "5",
    inWishlist: false,
    inStock: true,
  },
  {
    id:6,
    img: basicphones6,
    title: "Lava a1 vibe 2023",
    star: <AiFillStar className="rating-star" />,
    reviews: "(reviews)",
    prevPrice: "₹ 99,999",
    Price: "1249",
    company: "lowtohigh",
    color: "blue",
    category: "lava",
    discount: "5",
    inWishlist: false,
    inStock: true,
  },

   
   
  {
    id:7,
    img: basicphones7,
    title: "saregama carvaan m12 tamil",
    star: <AiFillStar className="rating-star" />,
    reviews: "(reviews)",
    prevPrice: "₹ 49,999",
    Price: "1699",
    company: "lowtohigh",
    color: "orange",
    category: "saregama",
    discount: "5",
    inWishlist: false,
    inStock: false,
  },
  
  {
    id:8,
    img: basicphones8,
    title: "saregama carvaan m22 tamil",
    star: <AiFillStar className="rating-star" />,
    reviews: "(reviews)",
    prevPrice: "₹ 40,999",
    Price: "2090",
    company: "lowtohigh",
    color: "black",
    category: "saregama",
    discount: "5",
    inWishlist: false,
    inStock: true,
  },
  {
    id:9,
    img: basicphones9,
    title: "itel super guru 600",
    star: <AiFillStar className="rating-star" />,
    reviews: "(reviews)",
    prevPrice: "₹ 10,999",
    Price: "1749",
    company: "lowtohigh",
    color: "gold",
    category: "itel",
    discount: "5",
    inWishlist: false,
    inStock: true,
  },
  {
    id:10,
    img: basicphones10,
    title: "Itel super guru 400",
    star: <AiFillStar className="rating-star" />,
    reviews: "(reviews)",
    prevPrice: "₹ 16,999",
    Price: "1699",
    company: "lowtohigh",
    color: "blue",
    category: "itel",
    discount: "5",
    inWishlist: false,
    inStock: true,
  },
  {
    id:11,
    img: basicphones11,
    title: "Samsung Guru Music 2  ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(reviews)",
    prevPrice: "₹ 16,999",
    Price: "2399",
    company: "lowtohigh",
    color: "black",
    category: "samsung",
    discount: "5",
    inWishlist: false,
    inStock: false,
  },
 
];

export default data;
